# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-28 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default=None, max_length=2500, null=True)),
                ('version', models.CharField(default=None, max_length=2500, null=True)),
                ('from_people', models.CharField(default=None, max_length=2500, null=True)),
                ('now_people', models.CharField(default=None, max_length=2500, null=True)),
            ],
        ),
    ]
