# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-28 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(max_length=500)),
                ('url_info', models.URLField()),
                ('request_type', models.IntegerField()),
                ('return_value', models.CharField(max_length=2500, null=True)),
                ('timeout', models.IntegerField(default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.Login')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='interfaceinfo',
            unique_together=set([('url_info', 'user')]),
        ),
    ]
