# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-04 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_info', models.URLField(unique=True)),
                ('status', models.IntegerField()),
                ('return_value', models.CharField(max_length=2500)),
                ('timeout', models.IntegerField(default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.Login')),
            ],
        ),
    ]
