# Generated by Django 2.0.4 on 2018-05-10 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaceinfo',
            name='request_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interfaceinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sign.Login'),
        ),
    ]
