# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-04 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HttpSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_url', models.URLField(null=True, unique=True)),
                ('status', models.IntegerField(default=1)),
                ('data', models.CharField(default=None, max_length=2500, null=True)),
                ('headers', models.CharField(default=None, max_length=2500, null=True)),
                ('cookie', models.CharField(default=None, max_length=2500, null=True)),
                ('send_type', models.CharField(max_length=50)),
                ('thread_num', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.Login')),
            ],
        ),
    ]
