# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('http_tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='httpsend',
            name='thread_num',
            field=models.ImageField(default=0, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='httpsend',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
