# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('http_tool', '0002_auto_20170701_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httpsend',
            name='thread_num',
            field=models.IntegerField(default=0),
        ),
    ]
