# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('http_tool', '0003_auto_20170701_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httpsend',
            name='cookie',
            field=models.CharField(default=None, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='httpsend',
            name='data',
            field=models.CharField(default=None, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='httpsend',
            name='headers',
            field=models.CharField(default=None, max_length=2500, null=True),
        ),
    ]
