# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HttpSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_url', models.URLField(null=True, unique=True)),
                ('status', models.IntegerField()),
                ('data', models.CharField(max_length=2500)),
                ('headers', models.CharField(max_length=2500)),
                ('cookie', models.CharField(max_length=2500)),
                ('send_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InterfaceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_info', models.URLField(unique=True)),
                ('status', models.IntegerField()),
                ('return_value', models.CharField(max_length=2500)),
                ('timeout', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(blank=True, default='0', max_length=50)),
                ('username', models.CharField(blank=True, max_length=50, unique=True)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('phone', models.IntegerField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='interfaceinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.Login'),
        ),
        migrations.AddField(
            model_name='httpsend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.Login'),
        ),
    ]
