# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaceinfo',
            name='url_info',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
