# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_auto_20170623_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_url', models.URLField(max_length=255)),
                ('return_data', models.CharField(max_length=1500)),
            ],
        ),
    ]
