# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_auto_20170627_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interfaceinfo',
            name='commit_type',
        ),
        migrations.AddField(
            model_name='interfaceinfo',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
