# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_auto_20170630_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaceinfo',
            name='timeout',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
