# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_auto_20170630_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
