# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_auto_20170627_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='HttpSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_url', models.URLField(null=True, unique=True)),
                ('status', models.IntegerField()),
                ('data', models.CharField(max_length=2500)),
                ('headers', models.CharField(max_length=2500)),
                ('cookie', models.CharField(max_length=2500)),
                ('send_type', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.Login')),
            ],
        ),
    ]
