# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0004_auto_20170630_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='httpsend',
            name='user',
        ),
        migrations.RemoveField(
            model_name='interfaceinfo',
            name='user',
        ),
        migrations.AlterField(
            model_name='login',
            name='phone',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='HttpSend',
        ),
        migrations.DeleteModel(
            name='InterfaceInfo',
        ),
    ]
