# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0005_auto_20170701_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
