# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0005_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaceinfo',
            name='url_info',
            field=models.URLField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
