# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0006_auto_20170629_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='phone',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
