# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-06 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automated_testing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('min', models.IntegerField(default=0)),
                ('max', models.IntegerField(default=0)),
                ('field', models.CharField(max_length=50)),
                ('is_null', models.CharField(default=0, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='caseconf',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='interfaceconf',
            name='is_null',
        ),
        migrations.RemoveField(
            model_name='interfaceconf',
            name='max',
        ),
        migrations.RemoveField(
            model_name='interfaceconf',
            name='min',
        ),
        migrations.RemoveField(
            model_name='interfaceconf',
            name='type',
        ),
        migrations.DeleteModel(
            name='CaseConf',
        ),
        migrations.AddField(
            model_name='interfaceattr',
            name='interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_testing.InterfaceConf'),
        ),
    ]
