# Generated by Django 2.0.4 on 2018-05-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_testing', '0003_auto_20180514_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='游戏名'),
        ),
    ]
