# Generated by Django 2.0.4 on 2018-05-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_testing', '0004_auto_20180514_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfaceattr',
            name='method',
            field=models.CharField(default='POST', max_length=500, verbose_name='请求方式'),
        ),
    ]
