# Generated by Django 2.0.4 on 2018-05-22 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automated_testing', '0005_interfaceattr_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interfaceattr',
            name='method',
        ),
    ]
