# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-24 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('smock_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u5192\u70df\u65f6\u95f4')),
                ('online_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4e0a\u7ebf\u65f6\u95f4')),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('project_name', models.CharField(max_length=200, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.Login')),
            ],
        ),
    ]
