# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-24 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='Participant',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='\u53c2\u4e0e\u4eba\u5458'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='project_manager',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='\u6d4b\u8bd5\u8d1f\u8d23\u4eba'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='project_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='\u9879\u76ee\u540d\u79f0'),
        ),
    ]
