# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-24 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_control', '0002_auto_20170724_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectinfo',
            old_name='Participant',
            new_name='participant',
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='current_phase',
            field=models.CharField(default='0', max_length=200, null=True, verbose_name='\u5f53\u524d\u9636\u6bb5'),
        ),
    ]
