# Generated by Django 2.0.4 on 2018-05-10 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_control', '0003_auto_20170724_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sign.Login'),
        ),
    ]
